#!/usr/bin/env bash

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "[DEV]: $@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

prompt_user() {
	input="USER INPUT"
	read -p "[PROMPT]: $1? [Y/n]: " input
	if [[ $input == [nN] ]]; then
		return 1
	else
		return 0
	fi
}
