#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

programs[0]=intellij-idea-community-edition-bin
programs[1]=zen-browser-bin
programs[2]=calibre-bin
programs[3]=obsidian
programs[4]=prismlauncher
programs[5]=jdk21-temurin

ask() {
	prompt_user "do you want to install - $1 - "
	retVal=$?
	if [ $retVal -eq 1 ]; then
		unset programs[$2]
		log "Ok, trying next program"
	fi
}

if [ ! -n "pacman -Qq | grep yay" ]; then
	prompt_user "yay is not installed, should i install yay"
	execute_d "cd $script_dir/../"
	log pwd
	execute_d "./dev yay"
else
	log "yay is installed, proceeding..."
	for i in {0..5}; do
		log "${programs[$i]}" "$i"
		ask "${programs[$i]}" "$i"
	done
	execute_d yay -S --disable-download-timeout --noconfirm ${programs[@]}
fi
