#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util
if [ ! -n "pacman -Qq | grep yay" ]; then
	prompt_user "yay is not installed, should i install yay"
	execute_d "cd $script_dir/../"
	log pwd
	execute_d "./dev yay"
else
	log "yay is installed, proceeding..."
	execute_d yay -S --noconfirm \
		neovim \
		fd \
		ripgrep \
		tmux \
		stow \
		btop \
		eza \
		fzf \
		fuse3 \
		ntfs-3g \
		zoxide \
		tokie \
		vlc \
		jq \
		nodejs \
		pnpm \
		go \
		rustup \
		kdeconnect
fi
