#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util
if [ ! -n "pacman -Qq | grep yay" ]; then
	depends_on yay
else
	log "yay is installed, proceeding..."
	execute_d yay -S \
		neovim-nightly-bin \
		fd \
		ripgrep \
		tmux \
		stow \
		btop \
		eza \
		ncdu \
		fzf \
		grimblast-git \
		swappy \
		pwvucontrol \
		nemo \
		fuse3 \
		ntfs-3g \
		zoxide \
		tokei \
		vlc \
		jq \
		nodejs \
    npm \
		pnpm \
		ly \
		go \
		rustup \
		kdeconnect \
    diff-so-fancy \
		--noconfirm
fi
