#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

if [ ! -n "pacman -Qq | grep yay" ]; then
	input="USER INPUT"
	read -p "yay is not installed, should i install yay? [Y/n]: " input
	if [[ $input == [nN] ]]; then
		log "Ok, exiting..."
		exit 0
	fi
	log "Installing yay..."
	cd $script_dir/../
	log pwd
	./dev yay
else
	execute yay -S --noconfirm \
		noto-fonts-emoji ttf-jetbrains-mono-nerd inter-font
fi
