#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

if [ ! -n "pacman -Qq | grep yay" ]; then
	depends_on yay
else
	execute_d yay -S --noconfirm \
		noto-fonts-emoji \
		ttf-jetbrains-mono-nerd \
		inter-font
fi
