#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

clone_repo() {
	if [ -d $HOME/Personal/$1 ]; then
		log "$1 exist trying next one..."
	else
		log "$1 dir does not exist, creating..."
		if [ -d $XDG_CONFIG_HOME/git ]; then
			execute_d git clone pox:$1.git $HOME/$2/$1
		else
			execute_d git clone git@github.com:PoXel6/$1.git $HOME/$2/$1
		fi
	fi
}

ask_to_clone() {
	prompt_user "Do you want to clone $1 repo"
	retVal=$?
	if [ $retVal -eq 1 ]; then
		log "Ok, trying next repo"
	else
		execute_d "clone_repo $1 $2"
	fi
}

if [ $# -ne 0 ]; then
	execute_d "clone_repo $1"
	exit 0
fi

[ -d $HOME/Personal/ ] || mkdir -p $HOME/Personal/

clone_repo CodeezNutz Persoanl
clone_repo dotConfig .
ask_to_clone PunishPlugin Personal
ask_to_clone Minion Personal
ask_to_clone brain-rot-clicker Personal

log "finished cloning repos"
