#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

execute_d cd $script_dir
if [ ! -d $HOME/dotConfig/ ]; then
	execute_d ./repo dotConfig
else
	log "dotConfig Already exist, proceeding"
fi
depends_on_prog stow
depends_on_prog find

stowing() {
	execute_d cd $HOME/dotConfig/
	find $HOME/dotConfig -maxdepth 1 -mindepth 1 -type d -not -path "*\.*" |
		sed "s|$HOME/dotConfig/||" |
		xargs -I{} stow -v2 {}
}

stowing D
stowing S
