#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

execute_d cd $script_dir
if [ ! -d $HOME/dotConfig/ ]; then
	execute_d ./repo dotConfig
elif [ ls /usr/bin/ | grep -q "stow" ]; then
	depends_on base
fi
log "dotConfig Already exist proceeding"

execute_d cd $HOME/dotConfig/
stowing() {
	execute_d stow -$1 zsh
	execute_d stow -$1 git
	execute_d stow -$1 hypr
	execute_d stow -$1 kitty
	execute_d stow -$1 waybar
	execute_d stow -$1 btop
	execute_d stow -$1 gtk-2.0
	execute_d stow -$1 gtk-3.0
	execute_d stow -$1 rofi
	execute_d stow -$1 scripts
	execute_d stow -$1 starship
	execute_d stow -$1 swappy
	execute_d stow -$1 swaync
	execute_d stow -$1 tmux
	execute_d stow -$1 waypaper
	execute_d stow -$1 keyd
	execute_d stow -$1 fastfetch
	execute_d stow -$1 bash
	execute_d stow -$1 nvim
}

stowing D
stowing S
