#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

execute_d sudo pacman -S --noconfirm --needed git base-devel
execute_d git clone https://aur.archlinux.org/yay.git $HOME/yay/
execute_d cd $HOME/yay/
execute_d makepkg -si
execute_d rm -rf $HOME/yay
execute_d yay -Syu --noconfirm
