#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $script_dir/../util

sudo pacman -S --noconfirm zsh
if [ "$(basename $(echo $SHELL))" = "zsh" ]; then
	log "User shell is alreay set to Zsh"
else
	execute chsh -s /usr/bin/zsh
  log "use 'zsh' to enter Zsh"
fi
